Query:
    type: object
    config:
        fields:
            user:
                type: "User"
                args:
                    id:
                        description: "ID of the user"
                        type: "Int!"
                resolve: "@=resolver('user', [args])"
            car:
                type: "Car"
                args:
                    id:
                        description: "ID of the car"
                        type: "Int!"
                resolve: "@=resolver('car', [args])"
